development:
  adapter: postgresql
  database: sport_sett_development
  user: postgres # Also accept 'username' as key, if both are present 'username' is used
  password: postgrespassword
  host: 127.0.0.1 # Optional
  port: 5432 # Optional
test:
  adapter: postgresql
  database: sport_sett_test
  user: postgres # Also accept 'username' as key, if both are present 'username' is used
  password: postgrespassword
  host: 127.0.0.1 # Optional
  port: 5432 # Optional
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
